export const skillExperience = [
  'Html',
  'Css',
  'html-5',
  'css-3',
  'Tailwind-css',
  'Bootstrap',
  'JavaScript',
  'React.js',
  'Next.js',
  'Redux-toolkit',
  'Context-api',
  'React query',
  'Ant Design',
  'Material ui',
  'psd to html',
]
